<!--
/**
 * Unicode Systems
 * @category   Uni
 * @package    Uni_Fileuploader
 * @copyright  Copyright (c) 2010-2011 Unicode Systems. (http://www.unicodesystems.in)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
 -->
<style type="text/css">
   a.prod-attach{text-decoration: none; cursor: pointer;}
   span.attach-img{float: left;}
   span.attach-title{float: left; text-decoration: underline;font-family: "montserratregular";}
</style>
<?php
$_product = Mage::registry('current_product');
$attachments = $this->getProductAttachments($_product->getId());
$_description = $_product->getDescription();
$version = substr(Mage::getVersion(), 0, 3);
?>
<div class="box-collateral box-description">
<div class="std">
<?php echo $_description; ?>
</div>
</div>
<?php 
if (count($attachments) > 0):
?>
<?php if ($_description && $version != '1.4'): ?></div><?php endif; ?>
    <div class="collateral-box box-collateral box-attachments">
    <?php if ($version == '1.3'): ?>
        <div class="head">
            <h4><?php echo $this->__('Product Attachments') ?></h4>
        </div>            
    <?php else: ?>
            <h2><?php echo $this->__('Product Attachments') ?></h2>
    <?php endif; ?>
            <div class="collateral-box attachment-specs">
                 <div class="std">

                <?php foreach ($attachments as $attachment): ?>
                         <?php echo $attachment['file']; ?>
                 <?php endforeach; ?>
                 </div>
            <script type="text/javascript">decorateTable('product-attachment-specs-table')</script>
        </div>
    <?php if (($_description == null) || $version == '1.4'): ?></div><?php endif; ?>
<?php endif; ?>