<script>
    jQuery(document).ready(function() {
      jQuery("#owl-demo2").owlCarousel({
        navigation : true,
	pagination:false
      });
    });
</script>
<?php
/**
 * M-Connect Solutions.
 *
 * NOTICE OF LICENSE
 *

 *
 * @category   Catalog
 * @package   Mconnect_Featuredproducts
 * @author      M-Connect Solutions (http://www.magentoconnect.us)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<h2 style="clear:both;"></h2>
<div id="owl-demo2" class="owl-carousel category-product">
<div class="slide" >
<a title="Mediwipes (Ctn of 12 disp)" class="product-image" href="<?php Mage::getBaseUrl();?>/gloves.html">
<img alt="" src="http://glowmile.com/demo/fine-touch/media/catalog/category/gloves_1.jpg">
</a>
<h2 class="product-name"><a href="<?php Mage::getBaseUrl();?>/gloves.html">Gloves</a></h2>
 
<button onclick="setLocation('<?php Mage::getBaseUrl();?>/gloves.html')" class="button btn-cart" title="Learn More" type="button"><span><span>Learn More</span></span></button>

</div>
<div class="slide" >
<a title="Mediwipes (Ctn of 12 disp)" class="product-image" href="<?php Mage::getBaseUrl();?>/gowns.html">
<img alt="" src="<?php Mage::getBaseUrl();?>/media/catalog/category/gowns.jpg">
</a>
<h2 class="product-name"><a href="<?php Mage::getBaseUrl();?>/gowns.html">Gowns</a></h2>
 
<button onclick="setLocation('<?php Mage::getBaseUrl();?>/gowns.html')" class="button btn-cart" title="Learn More" type="button"><span><span>Learn More</span></span></button>

</div>
<div class="slide" >
<a title="Mediwipes (Ctn of 12 disp)" class="product-image" href="<?php Mage::getBaseUrl();?>/hats.html">
<img alt="" src="<?php Mage::getBaseUrl();?>/media/catalog/category/hats_1.jpg">
</a>
<h2 class="product-name"><a href="<?php Mage::getBaseUrl();?>/hats.html">Hats</a></h2>
 
<button onclick="setLocation('<?php Mage::getBaseUrl();?>/hats.html')" class="button btn-cart" title="Learn More" type="button"><span><span>Learn More</span></span></button>

</div>
<div class="slide" >
<a title="Mediwipes (Ctn of 12 disp)" class="product-image" href="<?php Mage::getBaseUrl();?>/clothes.html">
<img alt="" src="<?php Mage::getBaseUrl();?>/media/catalog/category/clothing_1.jpg">
</a>
<h2 class="product-name"><a href="<?php Mage::getBaseUrl();?>/clothes.html">Clothes</a></h2>
 
<button onclick="setLocation('<?php Mage::getBaseUrl();?>/clothes.html')" class="button btn-cart" title="Learn More" type="button"><span><span>Learn More</span></span></button>

</div>
<div class="slide" >
<a title="Mediwipes (Ctn of 12 disp)" class="product-image" href="<?php Mage::getBaseUrl();?>/wipes.html">
<img alt="" src="<?php Mage::getBaseUrl();?>/media/catalog/category/Mediwipe_1.jpg">
</a>
<h2 class="product-name"><a href="<?php Mage::getBaseUrl();?>/wipes.html">Wipes</a></h2>
 
<button onclick="setLocation('<?php Mage::getBaseUrl();?>/wipes.html')" class="button btn-cart" title="Learn More" type="button"><span><span>Learn More</span></span></button>

</div>
<div class="slide" >
<a title="Mediwipes (Ctn of 12 disp)" class="product-image" href="<?php Mage::getBaseUrl();?>/miscellaneous.html">
<img alt="" src="<?php Mage::getBaseUrl();?>/media/catalog/category/HandSanitiserCrop_1.jpg">
</a>
<h2 class="product-name"><a href="<?php Mage::getBaseUrl();?>/miscellaneous.html">Miscellaneous</a></h2>
 
<button onclick="setLocation('<?php Mage::getBaseUrl();?>/miscellaneous.html')" class="button btn-cart" title="Learn More" type="button"><span><span>Learn More</span></span></button>

</div>
 
</div>
 
