<?php if(Mage::getSingleton('customer/session')->isLoggedIn() && Mage::getStoreConfig('creditlimitplus/parameters/enabled') && Mage::getStoreConfig('creditlimitplus/parameters/show_banner')){ ?>
	<div class="credit-limit-top">
		<div class="container">
			<?php $cretit_rules = $this->getCreditRules() ?>
			<?php if( count($cretit_rules) > 0){ ?>
				<ul class="clearfix">
					<?php foreach ($cretit_rules as $rule){ ?>
						<?php $used = $this->getUsedCredit( $rule->getId()   );?>
						<?php $remaining = $rule->getAmount() - $used ?>
						<li>
							<img src="<?php echo $rule->getLogo() ?>" alt="<?php echo $rule->getName()  ?>"/>
							<div>
								<span><?php echo Mage::helper("ecomwisecreditplus")->__('You have used') ?> <?php echo Mage::helper('core')->currency($used, true, false);?>
									<?php echo Mage::helper("ecomwisecreditplus")->__('of') ?> <?php echo Mage::helper('core')->currency($rule->getAmount(), true, false);?> </span>
									<br />
								<span class="remaining"><?php echo Mage::helper("ecomwisecreditplus")->__('Remaining:') ?> <?php echo Mage::helper('core')->currency($remaining, true, false);?> </span>
							</div>
						</li>
					<?php } ?>
				</ul>
			<?php } else { ?>
				<p><?php echo Mage::helper("ecomwisecreditplus")->__('You have no Credit limits.') ?></p>
			<?php } ?>
		</div>
	</div>
<?php } ?>
